// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go

// Package mock_follow_user_artist is a generated GoMock package.
package mock_follow_user_artist

import (
	model "followservice/internal/model/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// FollowUserArtist mocks base method.
func (m *MockService) FollowUserArtist(userPair *model.UserPairRelationship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowUserArtist", userPair)
	ret0, _ := ret[0].(error)
	return ret0
}

// FollowUserArtist indicates an expected call of FollowUserArtist.
func (mr *MockServiceMockRecorder) FollowUserArtist(userPair interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowUserArtist", reflect.TypeOf((*MockService)(nil).FollowUserArtist), userPair)
}
