// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_follow_user_artist is a generated GoMock package.
package mock_follow_user_artist

import (
	follow_user_artist "followservice/internal/features/follow_user_artist"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddUserRelation mocks base method.
func (m *MockRepository) AddUserRelation(data *follow_user_artist.UserPairFollowRelation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserRelation", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserRelation indicates an expected call of AddUserRelation.
func (mr *MockRepositoryMockRecorder) AddUserRelation(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserRelation", reflect.TypeOf((*MockRepository)(nil).AddUserRelation), data)
}
